import Header from "components/header";
import Hero from "components/hero";
import { hygraph } from "config/hygraph.config";
import { gql } from "graphql-request";
import type { NextPage } from "next";
import Head from "next/head";
import randomColor from "randomcolor";

interface IAuthor {
  id: string;
  name: string;
  email: string;
  phone: string;
  intro: string;
  bio: string;
  profession: string;
  picture: {
    url: string;
  };
}
interface ISocial {
  id: string;
  title: string;
  url: string;
}
interface ISkill {
  id: string;
  title: string;
}

export interface IUser {
  author: IAuthor;
  socials: ISocial[];
  skills: ISkill[];
  color: string;
}

interface Props {
  user: IUser;
}

const Home: NextPage<Props> = (props) => {
  console.log(props, "props");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {props?.user && <Hero user={props?.user} />}
    </>
  );
};

// from: https://hygraph.com/

const QUERY = gql`
  {
    socials {
      id
      title
      url
    }
    author(where: { slug: "md-eahea-ratan" }) {
      id
      name
      email
      phone
      intro
      bio
      profession
      picture {
        url
      }
    }
    skills {
      id
      title
    }
  }
`;

export async function getStaticProps() {
  try {
    const { author, socials, skills } = await hygraph.request(QUERY);

    return {
      props: {
        user: {
          author,
          socials,
          skills,
          color: randomColor({
            luminosity: "light",
          }),
        },
      },
    };
  } catch (err) {
    return { props: { error: err } };
  }
}

export default Home;
