import Header from "components/header";
import Hero from "components/hero";
import { hygraph } from "config/hygraph.config";
import { gql } from "graphql-request";
import type { NextPage } from "next";
import Head from "next/head";

interface IAuthor {
  id: string;
  name: string;
  intro: string;
  bio: string;
  profession: string;
  picture: {
    url: string;
  };
}
interface ISocials {
  facebookUrl: string;
  twitterUrl: string;
}

export interface IUser {
  author: IAuthor;
  socials: ISocials;
}

interface Props {
  user: IUser;
}

const Home: NextPage<Props> = ({ user }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero user={user} />
    </>
  );
};

const QUERY = gql`
  {
    socials {
      facebookUrl
      twitterUrl
    }
    author(where: { slug: "md-eahea-ratan" }) {
      id
      name
      intro
      bio
      profession
      picture {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { author, socials } = await hygraph.request(QUERY);

  return {
    props: {
      user: {
        author: author,
        socials: socials,
      },
    },
  };
}

export default Home;
